= Neo4j Graph Gist =
Anders Nawroth <anders@neotechnology.com>
v0.1, 2013-09-01
:neo4j-version: 2.0.0-RC1
:author: Anders Nawroth
:twitter: @nawroth

Neo4j GraphGists are a way to share documents including Cypher queries.
The queries can be executed in an online console.
GraphGists can be used to share examples or ideas or outline a question you have.

You create a GraphGist by creating a https://gist.github.com/[GitHub Gist] in http://asciidoctor.org/docs/asciidoc-quick-reference/[AsciiDoc] and enter the URL to it in the form on this page.
The GraphGist is just as private as the GitHub Gist you created.
To share a GraphGist, just share the URL the page gets after entering the Gist in the form.

For instructions, see:

* link:./?5956239[A simple GraphGist]
* link:./?5956246[How to create a GraphGist]

This is what the result can look like:

//console

A first simple query to just create a node:

[source,cypher]
----
CREATE (n {name:'first node'}) RETURN n;
----

NOTE: This document is a GraphGist, use the Page Source button on top of the page to see the Gist behind it.
